// Seed exercise library. Ids are slugs so the same exercise merges cleanly
// across devices without duplicating.
export const MUSCLE_GROUPS = [
  'Chest', 'Back', 'Shoulders', 'Biceps', 'Triceps', 'Forearms',
  'Quads', 'Hamstrings', 'Glutes', 'Calves', 'Core', 'Full Body', 'Cardio', 'Mobility', 'Other',
];

/** What an exercise is done with, for the create form and search. */
export const EQUIPMENT = [
  'Barbell', 'Dumbbell', 'Kettlebell', 'Machine', 'Smith machine', 'Cable',
  'Bodyweight', 'Band', 'Suspension', 'Medicine ball', 'Sandbag', 'Other',
];

// [name, group, equipment, defaultRestSec]
const SEED = [
  // Chest
  ['Barbell Bench Press', 'Chest', 'Barbell', 180],
  ['Incline Barbell Bench Press', 'Chest', 'Barbell', 180],
  ['Dumbbell Bench Press', 'Chest', 'Dumbbell', 150],
  ['Incline Dumbbell Press', 'Chest', 'Dumbbell', 150],
  ['Machine Chest Press', 'Chest', 'Machine', 120],
  ['Cable Fly', 'Chest', 'Cable', 90],
  ['Pec Deck', 'Chest', 'Machine', 90],
  ['Push-Up', 'Chest', 'Bodyweight', 90],
  ['Dip (Chest)', 'Chest', 'Bodyweight', 150],
  // Back
  ['Deadlift', 'Back', 'Barbell', 240],
  ['Barbell Row', 'Back', 'Barbell', 180],
  ['Pendlay Row', 'Back', 'Barbell', 180],
  ['Dumbbell Row', 'Back', 'Dumbbell', 120],
  ['Pull-Up', 'Back', 'Bodyweight', 150],
  ['Chin-Up', 'Back', 'Bodyweight', 150],
  ['Lat Pulldown', 'Back', 'Cable', 120],
  ['Pull-Up or Lat Pulldown', 'Back', 'Bar or cable', 120],
  ['Seated Cable Row', 'Back', 'Cable', 120],
  ['Chest-Supported Row', 'Back', 'Machine', 120],
  ['T-Bar Row', 'Back', 'Barbell', 150],
  ['Straight-Arm Pulldown', 'Back', 'Cable', 90],
  ['Face Pull', 'Back', 'Cable', 90],
  ['Rack Pull', 'Back', 'Barbell', 210],
  // Shoulders
  ['Overhead Press', 'Shoulders', 'Barbell', 180],
  ['Seated Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', 150],
  ['Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', 120],
  ['Arnold Press', 'Shoulders', 'Dumbbell', 120],
  ['Machine Shoulder Press', 'Shoulders', 'Machine', 120],
  ['Lateral Raise', 'Shoulders', 'Dumbbell', 75],
  ['Cable Lateral Raise', 'Shoulders', 'Cable', 75],
  ['Rear Delt Fly', 'Shoulders', 'Dumbbell', 75],
  ['Upright Row', 'Shoulders', 'Barbell', 90],
  ['Shrug', 'Shoulders', 'Dumbbell', 90],
  // Biceps
  ['Barbell Curl', 'Biceps', 'Barbell', 90],
  ['EZ-Bar Curl', 'Biceps', 'Barbell', 90],
  ['Dumbbell Curl', 'Biceps', 'Dumbbell', 90],
  ['Incline Dumbbell Curl', 'Biceps', 'Dumbbell', 90],
  ['Hammer Curl', 'Biceps', 'Dumbbell', 90],
  ['Preacher Curl', 'Biceps', 'Machine', 90],
  ['Cable Curl', 'Biceps', 'Cable', 75],
  // Triceps
  ['Close-Grip Bench Press', 'Triceps', 'Barbell', 150],
  ['Triceps Pushdown', 'Triceps', 'Cable', 75],
  ['Rope Pushdown', 'Triceps', 'Cable', 75],
  ['Overhead Cable Extension', 'Triceps', 'Cable', 90],
  ['Skullcrusher', 'Triceps', 'Barbell', 90],
  ['Dip (Triceps)', 'Triceps', 'Bodyweight', 150],
  ['Dumbbell Kickback', 'Triceps', 'Dumbbell', 60],
  // Quads
  ['Back Squat', 'Quads', 'Barbell', 210],
  ['Front Squat', 'Quads', 'Barbell', 210],
  ['Hack Squat', 'Quads', 'Machine', 180],
  ['Leg Press', 'Quads', 'Machine', 180],
  ['Bulgarian Split Squat', 'Quads', 'Dumbbell', 150],
  ['Dumbbell Split Squat', 'Quads', 'Dumbbell', 90],
  ['Walking Lunge', 'Quads', 'Dumbbell', 120],
  ['Goblet Squat', 'Quads', 'Dumbbell', 120],
  ['Leg Extension', 'Quads', 'Machine', 90],
  ['Step-Up', 'Quads', 'Dumbbell', 90],
  // Hamstrings
  ['Romanian Deadlift', 'Hamstrings', 'Barbell', 180],
  ['Stiff-Leg Deadlift', 'Hamstrings', 'Barbell', 180],
  ['Lying Leg Curl', 'Hamstrings', 'Machine', 90],
  ['Seated Leg Curl', 'Hamstrings', 'Machine', 90],
  ['Seated or Lying Leg Curl', 'Hamstrings', 'Machine', 90],
  ['Nordic Curl', 'Hamstrings', 'Bodyweight', 120],
  ['Good Morning', 'Hamstrings', 'Barbell', 150],
  // Glutes
  ['Hip Thrust', 'Glutes', 'Barbell', 150],
  ['Glute Bridge', 'Glutes', 'Barbell', 120],
  ['Cable Kickback', 'Glutes', 'Cable', 75],
  ['Hip Abduction', 'Glutes', 'Machine', 75],
  // Calves
  ['Standing Calf Raise', 'Calves', 'Machine', 75],
  ['Seated Calf Raise', 'Calves', 'Machine', 75],
  ['Leg Press Calf Raise', 'Calves', 'Machine', 75],
  // Core
  ['Plank', 'Core', 'Bodyweight', 60, 'time'],
  ['Side Plank', 'Core', 'Bodyweight', 45, 'time'],
  ['Hanging Leg Raise', 'Core', 'Bodyweight', 75],
  ['Hanging Knee Raise', 'Core', 'Bodyweight', 60],
  ['Cable Crunch', 'Core', 'Cable', 75],
  ['Ab Wheel Rollout', 'Core', 'Other', 75],
  ['Russian Twist', 'Core', 'Other', 60],
  ['Back Extension', 'Core', 'Machine', 90],
  ['Pallof Press', 'Core', 'Cable', 45],
  // Cardio
  ['Treadmill', 'Cardio', 'Machine', 0, 'time'],
  ['Rowing Machine', 'Cardio', 'Machine', 0, 'time'],
  ['Stationary Bike', 'Cardio', 'Machine', 0, 'time'],
  ['Stair Climber', 'Cardio', 'Machine', 0, 'time'],
  ['Elliptical', 'Cardio', 'Machine', 0, 'time'],
  ['Assault Bike', 'Cardio', 'Machine', 0, 'time'],
  ['Ski Erg', 'Cardio', 'Machine', 0, 'time'],
  ['Jump Rope', 'Cardio', 'Other', 60, 'time'],
  ['Battle Rope', 'Cardio', 'Other', 60, 'time'],
  ['Burpee', 'Cardio', 'Bodyweight', 60],
  ['Run', 'Cardio', 'Other', 0, 'time'],
  ['Easy Aerobic', 'Cardio', 'Other', 0, 'time'],
  ['Weighted Uphill Carry', 'Cardio', 'Other', 120, 'time'],
  // Olympic and power
  ['Power Clean', 'Back', 'Barbell', 180],
  ['Hang Power Clean', 'Back', 'Barbell', 180],
  ['Push Press', 'Shoulders', 'Barbell', 180],
  ['Thruster', 'Quads', 'Barbell', 120],
  ['Trap Bar Deadlift', 'Hamstrings', 'Barbell', 210],
  ['Deficit Deadlift', 'Back', 'Barbell', 240],
  ['Pause Squat', 'Quads', 'Barbell', 210],
  ['Landmine Press', 'Shoulders', 'Barbell', 90],
  // Plyometric
  ['Box Jump', 'Quads', 'Bodyweight', 120],
  ['Broad Jump', 'Quads', 'Bodyweight', 120],
  ['Depth Jump', 'Quads', 'Bodyweight', 150],
  ['Split Jump Squat', 'Quads', 'Bodyweight', 90],
  ['Squat Jump', 'Quads', 'Bodyweight', 90],
  ['Skater Bound', 'Glutes', 'Bodyweight', 90],
  ['Pogo Hop', 'Calves', 'Bodyweight', 60],
  ['Medicine Ball Slam', 'Core', 'Other', 60],
  ['Wall Ball', 'Quads', 'Other', 90],
  // Single leg and runner specific
  ['Single-Leg Romanian Deadlift', 'Hamstrings', 'Dumbbell', 90],
  ['Single-Leg Calf Raise', 'Calves', 'Bodyweight', 75],
  ['Single-Leg Glute Bridge', 'Glutes', 'Bodyweight', 60],
  ['Reverse Lunge', 'Quads', 'Dumbbell', 90],
  ['Front Lunge', 'Quads', 'Bodyweight', 60],
  ['Goblet Squat to Press', 'Quads', 'Dumbbell', 60],
  ['Floor Get-Up', 'Core', 'Bodyweight', 45],
  ['Lateral Lunge', 'Quads', 'Dumbbell', 90],
  ['Box Step-Up', 'Quads', 'Other', 60],
  ['Box Step-Down', 'Quads', 'Bodyweight', 60],
  ['Tibialis Raise', 'Calves', 'Bodyweight', 60],
  ['Monster Walk', 'Glutes', 'Other', 60],
  ['Hip Hike', 'Glutes', 'Bodyweight', 45],
  // Carries and sleds
  ['Farmer Carry', 'Core', 'Dumbbell', 90, 'time'],
  ['Suitcase Carry', 'Core', 'Dumbbell', 75, 'time'],
  ['Sled Push', 'Quads', 'Other', 120, 'time'],
  ['Sled Drag', 'Hamstrings', 'Other', 120, 'time'],
  ['Sandbag Carry', 'Core', 'Other', 120, 'time'],
  // Kettlebell
  ['Kettlebell Swing', 'Glutes', 'Kettlebell', 90],
  ['Turkish Get-Up', 'Core', 'Kettlebell', 120],
  ['Kettlebell Clean and Press', 'Shoulders', 'Kettlebell', 90],
  ['Kettlebell Front Squat', 'Quads', 'Kettlebell', 120],
  ['Kettlebell Snatch', 'Shoulders', 'Kettlebell', 90],
  ['Kettlebell Row', 'Back', 'Kettlebell', 90],
  // Bodyweight
  ['Inverted Row', 'Back', 'Bodyweight', 90],
  ['Pike Push-Up', 'Shoulders', 'Bodyweight', 90],
  ['Diamond Push-Up', 'Triceps', 'Bodyweight', 90],
  ['Pistol Squat', 'Quads', 'Bodyweight', 120],
  ['L-Sit', 'Core', 'Bodyweight', 90, 'time'],
  ['Handstand Hold', 'Shoulders', 'Bodyweight', 90, 'time'],
  ['Hollow Body Hold', 'Core', 'Bodyweight', 45, 'time'],
  ['Bear Crawl', 'Core', 'Bodyweight', 60, 'time'],
  ['Mountain Climber', 'Core', 'Bodyweight', 45, 'time'],
  ['Dead Bug', 'Core', 'Bodyweight', 45],
  ['Bird Dog', 'Core', 'Bodyweight', 45],
  ['Copenhagen Plank', 'Core', 'Bodyweight', 45, 'time'],
  // ---------------------------------------------------------------- more
  // A wider library: machine and cable variations, free-weight variations,
  // bodyweight and gymnastics progressions, functional and strongman work,
  // and mobility. [name, group, equipment, restSec, mode]
  // Chest
  ['Decline Barbell Bench Press', 'Chest', 'Barbell', 180],
  ['Decline Dumbbell Press', 'Chest', 'Dumbbell', 150],
  ['Floor Press', 'Chest', 'Barbell', 150],
  ['Dumbbell Floor Press', 'Chest', 'Dumbbell', 120],
  ['Dumbbell Squeeze Press', 'Chest', 'Dumbbell', 90],
  ['Dumbbell Fly', 'Chest', 'Dumbbell', 90],
  ['Incline Dumbbell Fly', 'Chest', 'Dumbbell', 90],
  ['Dumbbell Pullover', 'Chest', 'Dumbbell', 90],
  ['Low-to-High Cable Fly', 'Chest', 'Cable', 90],
  ['High-to-Low Cable Fly', 'Chest', 'Cable', 90],
  ['Single-Arm Cable Chest Press', 'Chest', 'Cable', 75],
  ['Incline Machine Chest Press', 'Chest', 'Machine', 120],
  ['Plate-Loaded Chest Press', 'Chest', 'Machine', 120],
  ['Smith Machine Bench Press', 'Chest', 'Smith machine', 150],
  ['Smith Machine Incline Press', 'Chest', 'Smith machine', 150],
  ['Landmine Chest Press', 'Chest', 'Barbell', 90],
  ['Svend Press', 'Chest', 'Other', 60],
  ['Incline Push-Up', 'Chest', 'Bodyweight', 60],
  ['Decline Push-Up', 'Chest', 'Bodyweight', 75],
  ['Weighted Push-Up', 'Chest', 'Other', 90],
  ['Archer Push-Up', 'Chest', 'Bodyweight', 90],
  ['Plyometric Push-Up', 'Chest', 'Bodyweight', 90],
  ['Pseudo Planche Push-Up', 'Chest', 'Bodyweight', 90],
  ['Ring Push-Up', 'Chest', 'Suspension', 90],
  ['Ring Dip', 'Chest', 'Suspension', 150],
  ['Suspension Chest Press', 'Chest', 'Suspension', 75],
  ['Band Chest Press', 'Chest', 'Band', 60],
  ['Medicine Ball Chest Pass', 'Chest', 'Medicine ball', 60],
  // Back
  ['Weighted Pull-Up', 'Back', 'Other', 180],
  ['Weighted Chin-Up', 'Back', 'Other', 180],
  ['Neutral-Grip Pull-Up', 'Back', 'Bodyweight', 150],
  ['Assisted Pull-Up', 'Back', 'Machine', 120],
  ['Band-Assisted Pull-Up', 'Back', 'Band', 120],
  ['Scapular Pull-Up', 'Back', 'Bodyweight', 60],
  ['Muscle-Up', 'Back', 'Bodyweight', 180],
  ['Front Lever Hold', 'Back', 'Bodyweight', 120, 'time'],
  ['Rope Climb', 'Back', 'Other', 180],
  ['Wide-Grip Lat Pulldown', 'Back', 'Cable', 120],
  ['Close-Grip Lat Pulldown', 'Back', 'Cable', 120],
  ['Single-Arm Lat Pulldown', 'Back', 'Cable', 90],
  ['Machine Lat Pulldown', 'Back', 'Machine', 120],
  ['Seated Row Machine', 'Back', 'Machine', 120],
  ['Plate-Loaded Row', 'Back', 'Machine', 120],
  ['Wide-Grip Cable Row', 'Back', 'Cable', 120],
  ['Single-Arm Cable Row', 'Back', 'Cable', 90],
  ['Cable Pullover', 'Back', 'Cable', 75],
  ['Yates Row', 'Back', 'Barbell', 150],
  ['Seal Row', 'Back', 'Barbell', 120],
  ['Meadows Row', 'Back', 'Barbell', 120],
  ['Landmine Row', 'Back', 'Barbell', 120],
  ['Chest-Supported Dumbbell Row', 'Back', 'Dumbbell', 90],
  ['Renegade Row', 'Back', 'Dumbbell', 90],
  ['Suspension Row', 'Back', 'Suspension', 75],
  ['Ring Row', 'Back', 'Suspension', 75],
  ['Band Row', 'Back', 'Band', 60],
  ['Band Pull-Apart', 'Back', 'Band', 45],
  ['Sumo Deadlift', 'Back', 'Barbell', 240],
  ['Snatch-Grip Deadlift', 'Back', 'Barbell', 240],
  ['Superman', 'Back', 'Bodyweight', 45],
  ['Sled Pull', 'Back', 'Other', 120, 'time'],
  // Shoulders
  ['Seated Barbell Overhead Press', 'Shoulders', 'Barbell', 150],
  ['Z Press', 'Shoulders', 'Barbell', 150],
  ['Push Jerk', 'Shoulders', 'Barbell', 180],
  ['Split Jerk', 'Shoulders', 'Barbell', 180],
  ['Single-Arm Dumbbell Shoulder Press', 'Shoulders', 'Dumbbell', 90],
  ['Smith Machine Shoulder Press', 'Shoulders', 'Smith machine', 120],
  ['Kettlebell Overhead Press', 'Shoulders', 'Kettlebell', 90],
  ['Bottoms-Up Kettlebell Press', 'Shoulders', 'Kettlebell', 90],
  ['Half-Kneeling Landmine Press', 'Shoulders', 'Barbell', 90],
  ['Handstand Push-Up', 'Shoulders', 'Bodyweight', 150],
  ['Wall Walk', 'Shoulders', 'Bodyweight', 90],
  ['Planche Lean', 'Shoulders', 'Bodyweight', 60, 'time'],
  ['Machine Lateral Raise', 'Shoulders', 'Machine', 75],
  ['Front Raise', 'Shoulders', 'Dumbbell', 75],
  ['Cable Front Raise', 'Shoulders', 'Cable', 60],
  ['Plate Front Raise', 'Shoulders', 'Other', 60],
  ['Reverse Pec Deck', 'Shoulders', 'Machine', 75],
  ['Cable Rear Delt Fly', 'Shoulders', 'Cable', 75],
  ['Incline Y Raise', 'Shoulders', 'Dumbbell', 60],
  ['Y-T-W Raise', 'Shoulders', 'Dumbbell', 45],
  ['Cuban Press', 'Shoulders', 'Dumbbell', 60],
  ['Cable External Rotation', 'Shoulders', 'Cable', 45],
  ['Band External Rotation', 'Shoulders', 'Band', 45],
  ['Kettlebell Halo', 'Shoulders', 'Kettlebell', 45],
  ['Barbell Shrug', 'Shoulders', 'Barbell', 90],
  ['Trap Bar Shrug', 'Shoulders', 'Barbell', 90],
  ['Overhead Carry', 'Shoulders', 'Dumbbell', 90, 'time'],
  ['Waiter Carry', 'Shoulders', 'Kettlebell', 60, 'time'],
  // Biceps
  ['Spider Curl', 'Biceps', 'Dumbbell', 75],
  ['Concentration Curl', 'Biceps', 'Dumbbell', 60],
  ['Dumbbell Preacher Curl', 'Biceps', 'Dumbbell', 75],
  ['EZ-Bar Preacher Curl', 'Biceps', 'Barbell', 90],
  ['Machine Curl', 'Biceps', 'Machine', 75],
  ['Bayesian Cable Curl', 'Biceps', 'Cable', 75],
  ['Rope Hammer Curl', 'Biceps', 'Cable', 75],
  ['Cross-Body Hammer Curl', 'Biceps', 'Dumbbell', 75],
  ['Zottman Curl', 'Biceps', 'Dumbbell', 75],
  ['Drag Curl', 'Biceps', 'Barbell', 75],
  ['Band Curl', 'Biceps', 'Band', 45],
  // Triceps
  ['Close-Grip Push-Up', 'Triceps', 'Bodyweight', 75],
  ['Bench Dip', 'Triceps', 'Bodyweight', 75],
  ['Seated Dip Machine', 'Triceps', 'Machine', 90],
  ['JM Press', 'Triceps', 'Barbell', 120],
  ['Dumbbell Skullcrusher', 'Triceps', 'Dumbbell', 90],
  ['Overhead Dumbbell Triceps Extension', 'Triceps', 'Dumbbell', 90],
  ['Tate Press', 'Triceps', 'Dumbbell', 75],
  ['Single-Arm Cable Pushdown', 'Triceps', 'Cable', 60],
  ['Cable Triceps Kickback', 'Triceps', 'Cable', 60],
  ['Machine Triceps Extension', 'Triceps', 'Machine', 75],
  ['Band Pushdown', 'Triceps', 'Band', 45],
  // Forearms and grip
  ['Wrist Curl', 'Forearms', 'Dumbbell', 45],
  ['Reverse Wrist Curl', 'Forearms', 'Dumbbell', 45],
  ['Reverse Curl', 'Forearms', 'Barbell', 75],
  ['Wrist Roller', 'Forearms', 'Other', 60],
  ['Plate Pinch', 'Forearms', 'Other', 60, 'time'],
  ['Dead Hang', 'Forearms', 'Bodyweight', 60, 'time'],
  ['Towel Hang', 'Forearms', 'Bodyweight', 75, 'time'],
  ['Hand Gripper', 'Forearms', 'Other', 45],
  // Quads
  ['Smith Machine Squat', 'Quads', 'Smith machine', 150],
  ['Safety Bar Squat', 'Quads', 'Barbell', 210],
  ['Box Squat', 'Quads', 'Barbell', 180],
  ['Zercher Squat', 'Quads', 'Barbell', 180],
  ['Overhead Squat', 'Quads', 'Barbell', 180],
  ['Belt Squat', 'Quads', 'Machine', 150],
  ['Pendulum Squat', 'Quads', 'Machine', 150],
  ['Dumbbell Squat', 'Quads', 'Dumbbell', 120],
  ['Heel-Elevated Goblet Squat', 'Quads', 'Dumbbell', 90],
  ['Single-Leg Leg Press', 'Quads', 'Machine', 90],
  ['Single-Leg Leg Extension', 'Quads', 'Machine', 60],
  ['Barbell Lunge', 'Quads', 'Barbell', 120],
  ['Barbell Reverse Lunge', 'Quads', 'Barbell', 120],
  ['Smith Machine Split Squat', 'Quads', 'Smith machine', 120],
  ['Front-Foot-Elevated Split Squat', 'Quads', 'Dumbbell', 120],
  ['Lateral Step-Up', 'Quads', 'Dumbbell', 75],
  ['Sandbag Lunge', 'Quads', 'Sandbag', 90],
  ['Air Squat', 'Quads', 'Bodyweight', 60],
  ['Cossack Squat', 'Quads', 'Bodyweight', 75],
  ['Shrimp Squat', 'Quads', 'Bodyweight', 90],
  ['Sissy Squat', 'Quads', 'Bodyweight', 75],
  ['Spanish Squat', 'Quads', 'Band', 60],
  ['Wall Sit', 'Quads', 'Bodyweight', 60, 'time'],
  ['Hip Adduction', 'Quads', 'Machine', 75],
  ['Tuck Jump', 'Quads', 'Bodyweight', 90],
  ['Hurdle Hop', 'Quads', 'Bodyweight', 90],
  // Hamstrings
  ['Dumbbell Romanian Deadlift', 'Hamstrings', 'Dumbbell', 120],
  ['B-Stance Romanian Deadlift', 'Hamstrings', 'Dumbbell', 90],
  ['Kettlebell Deadlift', 'Hamstrings', 'Kettlebell', 90],
  ['Standing Leg Curl', 'Hamstrings', 'Machine', 75],
  ['Glute-Ham Raise', 'Hamstrings', 'Machine', 120],
  ['Stability Ball Leg Curl', 'Hamstrings', 'Other', 60],
  ['Slider Leg Curl', 'Hamstrings', 'Other', 60],
  // Glutes
  ['Dumbbell Hip Thrust', 'Glutes', 'Dumbbell', 90],
  ['Smith Machine Hip Thrust', 'Glutes', 'Smith machine', 120],
  ['Hip Thrust Machine', 'Glutes', 'Machine', 120],
  ['Single-Leg Hip Thrust', 'Glutes', 'Bodyweight', 75],
  ['Cable Pull-Through', 'Glutes', 'Cable', 90],
  ['Reverse Hyperextension', 'Glutes', 'Machine', 90],
  ['Glute Kickback Machine', 'Glutes', 'Machine', 75],
  ['Cable Hip Abduction', 'Glutes', 'Cable', 60],
  ['Curtsy Lunge', 'Glutes', 'Dumbbell', 75],
  ['Lateral Band Walk', 'Glutes', 'Band', 45],
  ['Clamshell', 'Glutes', 'Band', 45],
  ['Frog Pump', 'Glutes', 'Bodyweight', 45],
  ['Fire Hydrant', 'Glutes', 'Bodyweight', 45],
  ['Donkey Kick', 'Glutes', 'Bodyweight', 45],
  ['Single-Arm Kettlebell Swing', 'Glutes', 'Kettlebell', 75],
  ['Lateral Bound', 'Glutes', 'Bodyweight', 90],
  // Calves
  ['Donkey Calf Raise', 'Calves', 'Machine', 75],
  ['Smith Machine Calf Raise', 'Calves', 'Smith machine', 75],
  ['Dumbbell Calf Raise', 'Calves', 'Dumbbell', 60],
  // Core
  ['Crunch', 'Core', 'Bodyweight', 45],
  ['Bicycle Crunch', 'Core', 'Bodyweight', 45],
  ['Reverse Crunch', 'Core', 'Bodyweight', 45],
  ['Sit-Up', 'Core', 'Bodyweight', 45],
  ['Decline Sit-Up', 'Core', 'Bodyweight', 60],
  ['V-Up', 'Core', 'Bodyweight', 45],
  ['Lying Leg Raise', 'Core', 'Bodyweight', 45],
  ['Toes-to-Bar', 'Core', 'Bodyweight', 75],
  ['Hanging Windscreen Wiper', 'Core', 'Bodyweight', 75],
  ['Dragon Flag', 'Core', 'Bodyweight', 90],
  ['Hollow Rock', 'Core', 'Bodyweight', 45],
  ['Flutter Kick', 'Core', 'Bodyweight', 45, 'time'],
  ['Plank Shoulder Tap', 'Core', 'Bodyweight', 45],
  ['Bear Plank', 'Core', 'Bodyweight', 45, 'time'],
  ['Stir the Pot', 'Core', 'Other', 45],
  ['Machine Crunch', 'Core', 'Machine', 60],
  ['Cable Woodchop', 'Core', 'Cable', 60],
  ['Landmine Rotation', 'Core', 'Barbell', 60],
  ['Dumbbell Side Bend', 'Core', 'Dumbbell', 45],
  ['Suitcase Deadlift', 'Core', 'Dumbbell', 75],
  ['Kettlebell Windmill', 'Core', 'Kettlebell', 60],
  ['Front Rack Carry', 'Core', 'Kettlebell', 90, 'time'],
  ['Medicine Ball Rotational Throw', 'Core', 'Medicine ball', 60],
  // Full body and functional
  ['Clean and Jerk', 'Full Body', 'Barbell', 180],
  ['Squat Clean', 'Full Body', 'Barbell', 180],
  ['Clean Pull', 'Full Body', 'Barbell', 150],
  ['Power Snatch', 'Full Body', 'Barbell', 180],
  ['Hang Power Snatch', 'Full Body', 'Barbell', 180],
  ['Dumbbell Snatch', 'Full Body', 'Dumbbell', 90],
  ['Dumbbell Clean and Press', 'Full Body', 'Dumbbell', 90],
  ['Dumbbell Thruster', 'Full Body', 'Dumbbell', 90],
  ['Devil Press', 'Full Body', 'Dumbbell', 90],
  ['Man Maker', 'Full Body', 'Dumbbell', 90],
  ['Kettlebell Clean', 'Full Body', 'Kettlebell', 90],
  ['Kettlebell High Pull', 'Full Body', 'Kettlebell', 75],
  ['Burpee Broad Jump', 'Full Body', 'Bodyweight', 90],
  ['Burpee Box Jump-Over', 'Full Body', 'Bodyweight', 90],
  ['Inchworm', 'Full Body', 'Bodyweight', 45],
  ['Sandbag Clean', 'Full Body', 'Sandbag', 90],
  ['Sandbag to Shoulder', 'Full Body', 'Sandbag', 90],
  ['Atlas Stone Lift', 'Full Body', 'Other', 150],
  ['Tyre Flip', 'Full Body', 'Other', 120],
  ['Sledgehammer Strike', 'Full Body', 'Other', 60],
  ['Yoke Carry', 'Full Body', 'Other', 150, 'time'],
  // Cardio and conditioning
  ['Sprint', 'Cardio', 'Other', 120],
  ['Hill Sprint', 'Cardio', 'Other', 120],
  ['Shuttle Run', 'Cardio', 'Other', 60],
  ['Incline Treadmill Walk', 'Cardio', 'Machine', 0, 'time'],
  ['Cycling', 'Cardio', 'Other', 0, 'time'],
  ['Swim', 'Cardio', 'Other', 0, 'time'],
  ['Jumping Jack', 'Cardio', 'Bodyweight', 30, 'time'],
  ['High Knees', 'Cardio', 'Bodyweight', 30, 'time'],
  // Mobility
  ['Cat-Cow', 'Mobility', 'Bodyweight', 30],
  ["World's Greatest Stretch", 'Mobility', 'Bodyweight', 30],
  ['90/90 Hip Switch', 'Mobility', 'Bodyweight', 30],
  ['Couch Stretch', 'Mobility', 'Bodyweight', 30, 'time'],
  ['Hip Flexor Stretch', 'Mobility', 'Bodyweight', 30, 'time'],
  ['Pigeon Stretch', 'Mobility', 'Bodyweight', 30, 'time'],
  ['Open Book Rotation', 'Mobility', 'Bodyweight', 30],
  ['Thread the Needle', 'Mobility', 'Bodyweight', 30],
  ['Knee-to-Wall Ankle Mobilisation', 'Mobility', 'Bodyweight', 30],
  ['Deep Squat Hold', 'Mobility', 'Bodyweight', 30, 'time'],
  ['Band Shoulder Pass-Through', 'Mobility', 'Band', 30],
  ['Foam Roll', 'Mobility', 'Other', 0, 'time'],
];

export function slugify(str) {
  return String(str)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

/**
 * Where to go to see a movement performed.
 *
 * A curated `video` on the exercise wins. Otherwise this returns a search
 * rather than a single hand-picked clip: a search never rots, covers the
 * exercises you add yourself, and does not quietly send you to a video that
 * was taken down a year ago. Nothing is embedded — the link opens in the
 * browser, so no third-party player loads inside the app.
 */
export function howToUrl(exercise) {
  if (exercise?.video) return exercise.video;
  const name = String(exercise?.name || '').trim();
  if (!name) return null;
  const q = encodeURIComponent(`how to ${name} proper form technique`);
  return `https://www.youtube.com/results?search_query=${q}`;
}

/** Compare names ignoring case, spacing and punctuation. */
export function nameKey(name) {
  return String(name ?? '').toLowerCase().replace(/[^a-z0-9]/g, '');
}

/**
 * Other names for exercises already in the library. A plan written as
 * "Dumbbell Lateral Raise" means the Lateral Raise here; giving it an entry of
 * its own would split one movement's progress across two exercises.
 *
 * Only names that are unambiguously the same movement belong here. Seated
 * versus standing, or rear foot up versus down, are different exercises and
 * get entries of their own instead.
 */
const ALIASES = {
  'Triceps Rope Pushdown': 'Rope Pushdown',
  'Tricep Rope Pushdown': 'Rope Pushdown',
  'Tricep Pushdown': 'Triceps Pushdown',
  'Dumbbell Lateral Raise': 'Lateral Raise',
  'DB Lateral Raise': 'Lateral Raise',
  'Overhead Cable Triceps Extension': 'Overhead Cable Extension',
  'Overhead Cable Tricep Extension': 'Overhead Cable Extension',
  'Single Arm Dumbbell Row': 'Dumbbell Row',
  'One Arm Dumbbell Row': 'Dumbbell Row',
  'Standing Overhead Press': 'Overhead Press',
  'Barbell Overhead Press': 'Overhead Press',
  'Pullup': 'Pull-Up',
  'Chinup': 'Chin-Up',
};

const ALIAS_IDS = new Map(Object.entries(ALIASES).map(([alias, name]) => [nameKey(alias), slugify(name)]));

/** The library id another name for an exercise stands for, if it is one. */
export function aliasId(name) {
  return ALIAS_IDS.get(nameKey(name)) || null;
}

export const SEED_EXERCISES = SEED.map(([name, group, equipment, restSec, mode]) => ({
  id: slugify(name),
  name,
  group,
  equipment,
  restSec,
  ...(mode && { mode }),
}));
